name: Mirror Commits to GitLab

on:
  push: #when a direct push to the main is done
    branches:
      - main
  pull_request:  # when a pull request (to the main) closed 
    types: [closed]
    branches:
      - main
      
jobs:
  mirror-commits:
    runs-on: ubuntu-latest  #ubuntu-latest used in GitHub Actions comes with Git pre-installed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) # let the mirroring pass only when the pull request is merged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add GitLab remote
        env:
          GITLAB_REPO_URL: https://github.com/brahimboufous/GitTraining.git
        run: |
          git remote add gitlab ${GITLAB_REPO_URL}
          git remote set-url gitlab ${GITLAB_REPO_URL}
          git config --local credential.helper 'store --file=.git/credentials'
          echo "https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_PASSWORD }}@github.com/brahimboufous/GitTraining.git" >> .git/credentials
          cat .git/credentials
          ls -a
      - name: push to GitLab
        run: |
          git clone https://github.com/brahimboufous/GitTraining.git
