name: Mirror Commits to GitLab

on:
  push: #when a direct push to the main is done
    branches:
      - main
  pull_request:  # when a pull request (to the main) closed 
    types: [closed]
    branches:
      - main
      
jobs:
  mirror-commits:
    runs-on: ubuntu-latest  #ubuntu-latest used in GitHub Actions comes with Git pre-installed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) # let the mirroring pass only when the pull request is merged
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://github.com/brahimboufous/GitTraining.git'
            GIT_USERNAME: 'boufousbrahim'
            GIT_PASSWORD: 'G746120boufous' 
