name: Mirror Commits to GitLab

on:
  push: #when a direct push to the main is done
    branches:
      - main
  pull_request:  # when a pull request (to the main) closed 
    types: [closed]
    branches:
      - main
      
jobs:
  mirror-commits:
    runs-on: ubuntu-latest  #ubuntu-latest used in GitHub Actions comes with Git pre-installed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) # let the mirroring pass only when the pull request is merged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add GitLab remote
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_REPO_URL: https://github.com/brahimboufous/GitTraining.git
        run: |
          git remote add gitlab ${GITLAB_REPO_URL}
          git remote set-url origin ${GITLAB_REPO_URL}
          git config --local credential.helper 'store --file=.git/credentials'
          echo "https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@${GITLAB_REPO_URL}" >> .git/credentials
          echo "https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@${GITLAB_REPO_URL}"
          ls
      - name: push to GitLab
        run: |
          git push origin HEAD:main 
          git push gitlab HEAD:main 
